import 'dotenv/config'

import { PrismaPg } from '@prisma/adapter-pg'
import { PrismaClient } from '../src/generated/prisma/index.js'

const databaseUrl =
  process.env.DATABASE_URL ??
  'postgresql://postgres:postgres@localhost:5432/caregiver_ai?schema=public'

const adapter = new PrismaPg({ connectionString: databaseUrl })
const prisma = new PrismaClient({ adapter })

// ---------------------------------------------------------------------------
// Canadian plan data based on real Sun Life and provincial plan structures
// ---------------------------------------------------------------------------

const canadianPlans = [
  {
    sourceFile: 'Sunlife Healthcare Plan Documents/Basic Plan.md',
    planName: 'Sun Life Basic Plan',
    planType: 'private_individual',
    carrier: 'Sun Life Financial',
    jurisdiction: 'Canada',
    extractionConfidence: 'high',
    extractedData: {
      planName: 'Sun Life Basic Plan',
      planType: 'private_individual',
      carrier: 'Sun Life Financial',
      jurisdiction: 'Canada',
      effectiveDate: '2024-01-01',
      summary: 'An affordable entry-level health insurance plan from Sun Life Financial providing essential coverage for prescription drugs, dental care, and vision care. Designed for individuals and families seeking basic supplemental coverage beyond provincial health plans.',
      eligibility: {
        eligiblePopulations: ['Canadian residents', 'permanent residents', 'work permit holders'],
        ageRestrictions: '18-65 for new enrollees',
        residencyRequirements: 'Must be a resident of a Canadian province or territory with valid provincial health coverage',
        incomeRequirements: null,
        employmentRequirements: null,
        waitingPeriodDays: 30,
      },
      costStructure: {
        premiumType: 'individual_paid',
        monthlyPremiumEstimate: 65,
        deductible: 50,
        coinsuranceDefault: 70,
        maxOutOfPocket: 2000,
        hasIncomeTieredCopay: false,
        incomeTiers: [],
      },
      benefits: [
        { category: 'prescription_drugs', covered: true, reimbursementPct: 70, annualMaximum: 1500, lifetimeMaximum: null, copay: null, waitingPeriodDays: 30, preauthorizationRequired: false, notes: 'Generic substitution required when available. Brand name drugs covered at 60%.' },
        { category: 'dental', covered: true, reimbursementPct: 60, annualMaximum: 500, lifetimeMaximum: null, copay: null, waitingPeriodDays: 90, preauthorizationRequired: false, notes: 'Basic dental only: exams, cleanings, fillings. No orthodontics or major restorative.' },
        { category: 'vision', covered: true, reimbursementPct: 100, annualMaximum: 150, lifetimeMaximum: null, copay: null, waitingPeriodDays: 0, preauthorizationRequired: false, notes: 'Eye exams every 24 months. $150 maximum for frames and lenses every 24 months.' },
        { category: 'hospital', covered: false, reimbursementPct: null, annualMaximum: null, lifetimeMaximum: null, copay: null, waitingPeriodDays: null, preauthorizationRequired: false, notes: 'Hospital services covered by provincial health plan.' },
        { category: 'mental_health', covered: true, reimbursementPct: 70, annualMaximum: 300, lifetimeMaximum: null, copay: null, waitingPeriodDays: 0, preauthorizationRequired: false, notes: 'Psychologist and social worker visits. $300 combined annual maximum.' },
        { category: 'emergency', covered: false, reimbursementPct: null, annualMaximum: null, lifetimeMaximum: null, copay: null, waitingPeriodDays: null, preauthorizationRequired: false, notes: 'Emergency services covered by provincial health plan.' },
        { category: 'travel_medical', covered: true, reimbursementPct: 100, annualMaximum: 1000000, lifetimeMaximum: null, copay: null, waitingPeriodDays: 0, preauthorizationRequired: false, notes: 'Emergency medical coverage while travelling outside Canada. 15-day maximum per trip.' },
        { category: 'physiotherapy', covered: true, reimbursementPct: 70, annualMaximum: 300, lifetimeMaximum: null, copay: null, waitingPeriodDays: 0, preauthorizationRequired: false, notes: '$300 annual maximum for physiotherapy.' },
      ],
      exclusions: ['Cosmetic procedures', 'Experimental treatments', 'Pre-existing conditions (12-month exclusion period)', 'Orthodontics'],
      claimsProcess: 'Submit claims online through mysunlife.ca or the Sun Life mobile app within 12 months of service.',
      renewalTerms: 'Automatically renews annually. Premiums may be adjusted at renewal.',
      sourceFile: 'Sunlife Healthcare Plan Documents/Basic Plan.md',
      extractionConfidence: 'high',
    },
    mlFeatures: {
      planId: 'sun-life-financial-sun-life-basic-plan',
      planName: 'Sun Life Basic Plan',
      planType: 'private_individual',
      carrier: 'Sun Life Financial',
      jurisdiction: 'Canada',
      monthlyPremiumEstimate: 65,
      deductible: 50,
      coinsuranceDefault: 70,
      maxOutOfPocket: 2000,
      totalBenefitCategories: 8,
      coveredBenefitCount: 6,
      preauthorizationRequiredCount: 0,
      coversPrescriptionDrugs: true,
      coversDental: true,
      coversVision: true,
      coversHospital: false,
      coversMentalHealth: true,
      coversEmergency: false,
      coversTravelMedical: true,
      coversSpecialist: false,
      coversPhysiotherapy: true,
      coversChiropractic: false,
      avgReimbursementPct: 72,
      minReimbursementPct: 60,
      maxReimbursementPct: 100,
      isPublic: false,
      hasIncomeRequirement: false,
      hasResidencyRequirement: true,
      hasWaitingPeriod: true,
      exclusionCount: 4,
      hasIncomeTieredCopay: false,
      overallGenerosity: 'basic',
      bestForProfile: 'Young, healthy Canadians who want affordable supplemental coverage for prescriptions and dental beyond their provincial plan.',
      featureVector: {
        plan_type: 'private_individual', jurisdiction: 'Canada', is_public: false,
        monthly_premium: 65, deductible: 50, coinsurance_default: 70, max_oop: 2000,
        covered_count: 6, total_categories: 8, coverage_ratio: 75, preauth_count: 0,
        covers_drugs: true, covers_dental: true, covers_vision: true, covers_hospital: false,
        covers_mental_health: true, covers_emergency: false, covers_travel: true,
        covers_specialist: false, covers_physio: true, covers_chiro: false,
        avg_reimbursement: 72, min_reimbursement: 60, max_reimbursement: 100,
        has_income_requirement: false, has_residency_requirement: true,
        has_waiting_period: true, exclusion_count: 4, has_income_tiered_copay: false,
        generosity: 'basic',
      },
    },
  },
  {
    sourceFile: 'Sunlife Healthcare Plan Documents/Standard Plan.md',
    planName: 'Sun Life Standard Plan',
    planType: 'private_individual',
    carrier: 'Sun Life Financial',
    jurisdiction: 'Canada',
    extractionConfidence: 'high',
    extractedData: {
      planName: 'Sun Life Standard Plan',
      planType: 'private_individual',
      carrier: 'Sun Life Financial',
      jurisdiction: 'Canada',
      effectiveDate: '2024-01-01',
      summary: 'A mid-tier health insurance plan from Sun Life Financial offering balanced coverage for prescription drugs, dental, vision, mental health, and paramedical services. Popular choice for individuals and families wanting solid protection without premium pricing.',
      eligibility: {
        eligiblePopulations: ['Canadian residents', 'permanent residents', 'work permit holders'],
        ageRestrictions: '18-65 for new enrollees',
        residencyRequirements: 'Must be a resident of a Canadian province or territory with valid provincial health coverage',
        incomeRequirements: null,
        employmentRequirements: null,
        waitingPeriodDays: 0,
      },
      costStructure: {
        premiumType: 'individual_paid',
        monthlyPremiumEstimate: 120,
        deductible: 25,
        coinsuranceDefault: 80,
        maxOutOfPocket: 3000,
        hasIncomeTieredCopay: false,
        incomeTiers: [],
      },
      benefits: [
        { category: 'prescription_drugs', covered: true, reimbursementPct: 80, annualMaximum: 5000, lifetimeMaximum: null, copay: null, waitingPeriodDays: 0, preauthorizationRequired: false, notes: 'Generic and brand name drugs covered. Prior authorization for specialty drugs over $500/month.' },
        { category: 'dental', covered: true, reimbursementPct: 80, annualMaximum: 1500, lifetimeMaximum: null, copay: null, waitingPeriodDays: 0, preauthorizationRequired: false, notes: 'Basic and major restorative dental. Orthodontics covered at 50% to $2000 lifetime max.' },
        { category: 'vision', covered: true, reimbursementPct: 100, annualMaximum: 300, lifetimeMaximum: null, copay: null, waitingPeriodDays: 0, preauthorizationRequired: false, notes: 'Eye exams every 12 months. $300 maximum for frames and lenses every 24 months.' },
        { category: 'hospital', covered: true, reimbursementPct: 100, annualMaximum: null, lifetimeMaximum: null, copay: null, waitingPeriodDays: 0, preauthorizationRequired: false, notes: 'Semi-private hospital room coverage.' },
        { category: 'mental_health', covered: true, reimbursementPct: 80, annualMaximum: 1000, lifetimeMaximum: null, copay: null, waitingPeriodDays: 0, preauthorizationRequired: false, notes: 'Psychologist, social worker, and registered counsellor visits.' },
        { category: 'emergency', covered: true, reimbursementPct: 100, annualMaximum: null, lifetimeMaximum: null, copay: null, waitingPeriodDays: 0, preauthorizationRequired: false, notes: 'Ambulance services covered at 100%.' },
        { category: 'travel_medical', covered: true, reimbursementPct: 100, annualMaximum: 5000000, lifetimeMaximum: null, copay: null, waitingPeriodDays: 0, preauthorizationRequired: false, notes: 'Emergency medical coverage while travelling outside Canada. 30-day maximum per trip.' },
        { category: 'specialist', covered: true, reimbursementPct: 80, annualMaximum: 500, lifetimeMaximum: null, copay: null, waitingPeriodDays: 0, preauthorizationRequired: true, notes: 'Specialist referral required. Pre-authorization for high-cost treatments.' },
        { category: 'physiotherapy', covered: true, reimbursementPct: 80, annualMaximum: 750, lifetimeMaximum: null, copay: null, waitingPeriodDays: 0, preauthorizationRequired: false, notes: '$750 annual maximum for physiotherapy.' },
        { category: 'chiropractic', covered: true, reimbursementPct: 80, annualMaximum: 500, lifetimeMaximum: null, copay: null, waitingPeriodDays: 0, preauthorizationRequired: false, notes: '$500 annual maximum for chiropractic care.' },
      ],
      exclusions: ['Cosmetic procedures', 'Experimental treatments', 'Fertility treatments', 'Weight loss surgery'],
      claimsProcess: 'Submit claims online through mysunlife.ca or the Sun Life mobile app within 12 months of service.',
      renewalTerms: 'Automatically renews annually. Premiums may be adjusted at renewal.',
      sourceFile: 'Sunlife Healthcare Plan Documents/Standard Plan.md',
      extractionConfidence: 'high',
    },
    mlFeatures: {
      planId: 'sun-life-financial-sun-life-standard-plan',
      planName: 'Sun Life Standard Plan',
      planType: 'private_individual',
      carrier: 'Sun Life Financial',
      jurisdiction: 'Canada',
      monthlyPremiumEstimate: 120,
      deductible: 25,
      coinsuranceDefault: 80,
      maxOutOfPocket: 3000,
      totalBenefitCategories: 10,
      coveredBenefitCount: 10,
      preauthorizationRequiredCount: 1,
      coversPrescriptionDrugs: true,
      coversDental: true,
      coversVision: true,
      coversHospital: true,
      coversMentalHealth: true,
      coversEmergency: true,
      coversTravelMedical: true,
      coversSpecialist: true,
      coversPhysiotherapy: true,
      coversChiropractic: true,
      avgReimbursementPct: 88,
      minReimbursementPct: 80,
      maxReimbursementPct: 100,
      isPublic: false,
      hasIncomeRequirement: false,
      hasResidencyRequirement: true,
      hasWaitingPeriod: false,
      exclusionCount: 4,
      hasIncomeTieredCopay: false,
      overallGenerosity: 'comprehensive',
      bestForProfile: 'Families and working professionals who want well-rounded coverage including dental, drugs, and mental health without paying premium prices.',
      featureVector: {
        plan_type: 'private_individual', jurisdiction: 'Canada', is_public: false,
        monthly_premium: 120, deductible: 25, coinsurance_default: 80, max_oop: 3000,
        covered_count: 10, total_categories: 10, coverage_ratio: 100, preauth_count: 1,
        covers_drugs: true, covers_dental: true, covers_vision: true, covers_hospital: true,
        covers_mental_health: true, covers_emergency: true, covers_travel: true,
        covers_specialist: true, covers_physio: true, covers_chiro: true,
        avg_reimbursement: 88, min_reimbursement: 80, max_reimbursement: 100,
        has_income_requirement: false, has_residency_requirement: true,
        has_waiting_period: false, exclusion_count: 4, has_income_tiered_copay: false,
        generosity: 'comprehensive',
      },
    },
  },
  {
    sourceFile: 'Sunlife Healthcare Plan Documents/Enhanced Plan.md',
    planName: 'Sun Life Enhanced Plan',
    planType: 'private_individual',
    carrier: 'Sun Life Financial',
    jurisdiction: 'Canada',
    extractionConfidence: 'high',
    extractedData: {
      planName: 'Sun Life Enhanced Plan',
      planType: 'private_individual',
      carrier: 'Sun Life Financial',
      jurisdiction: 'Canada',
      effectiveDate: '2024-01-01',
      summary: 'The premium tier Sun Life health insurance plan offering the highest reimbursement rates, largest annual maximums, and broadest coverage. Includes enhanced mental health, paramedical services, and fertility treatment coverage not available in lower tiers.',
      eligibility: {
        eligiblePopulations: ['Canadian residents', 'permanent residents', 'work permit holders'],
        ageRestrictions: '18-65 for new enrollees',
        residencyRequirements: 'Must be a resident of a Canadian province or territory with valid provincial health coverage',
        incomeRequirements: null,
        employmentRequirements: null,
        waitingPeriodDays: 0,
      },
      costStructure: {
        premiumType: 'individual_paid',
        monthlyPremiumEstimate: 195,
        deductible: 0,
        coinsuranceDefault: 90,
        maxOutOfPocket: 1500,
        hasIncomeTieredCopay: false,
        incomeTiers: [],
      },
      benefits: [
        { category: 'prescription_drugs', covered: true, reimbursementPct: 90, annualMaximum: 10000, lifetimeMaximum: null, copay: null, waitingPeriodDays: 0, preauthorizationRequired: false, notes: 'Generic and brand name drugs covered at 90%. Specialty drugs covered with prior authorization.' },
        { category: 'dental', covered: true, reimbursementPct: 90, annualMaximum: 3000, lifetimeMaximum: null, copay: null, waitingPeriodDays: 0, preauthorizationRequired: false, notes: 'Basic, major restorative, and orthodontics. Orthodontics at 60% to $3000 lifetime max.' },
        { category: 'vision', covered: true, reimbursementPct: 100, annualMaximum: 500, lifetimeMaximum: null, copay: null, waitingPeriodDays: 0, preauthorizationRequired: false, notes: 'Eye exams every 12 months. $500 maximum for frames, lenses, or contacts every 24 months. Laser eye surgery covered to $1000 lifetime.' },
        { category: 'hospital', covered: true, reimbursementPct: 100, annualMaximum: null, lifetimeMaximum: null, copay: null, waitingPeriodDays: 0, preauthorizationRequired: false, notes: 'Private hospital room coverage.' },
        { category: 'mental_health', covered: true, reimbursementPct: 90, annualMaximum: 3000, lifetimeMaximum: null, copay: null, waitingPeriodDays: 0, preauthorizationRequired: false, notes: 'Psychologist, psychiatrist, social worker, and registered counsellor visits. Includes online therapy.' },
        { category: 'emergency', covered: true, reimbursementPct: 100, annualMaximum: null, lifetimeMaximum: null, copay: null, waitingPeriodDays: 0, preauthorizationRequired: false, notes: 'Ambulance and emergency services covered at 100%.' },
        { category: 'travel_medical', covered: true, reimbursementPct: 100, annualMaximum: 10000000, lifetimeMaximum: null, copay: null, waitingPeriodDays: 0, preauthorizationRequired: false, notes: 'Emergency medical coverage while travelling outside Canada. 60-day maximum per trip.' },
        { category: 'specialist', covered: true, reimbursementPct: 90, annualMaximum: 1000, lifetimeMaximum: null, copay: null, waitingPeriodDays: 0, preauthorizationRequired: false, notes: 'Specialist visits covered. No referral required.' },
        { category: 'physiotherapy', covered: true, reimbursementPct: 90, annualMaximum: 1500, lifetimeMaximum: null, copay: null, waitingPeriodDays: 0, preauthorizationRequired: false, notes: '$1500 annual maximum for physiotherapy.' },
        { category: 'chiropractic', covered: true, reimbursementPct: 90, annualMaximum: 750, lifetimeMaximum: null, copay: null, waitingPeriodDays: 0, preauthorizationRequired: false, notes: '$750 annual maximum for chiropractic care.' },
        { category: 'massage', covered: true, reimbursementPct: 80, annualMaximum: 750, lifetimeMaximum: null, copay: null, waitingPeriodDays: 0, preauthorizationRequired: false, notes: 'Registered massage therapy. $750 annual maximum.' },
        { category: 'naturopath', covered: true, reimbursementPct: 80, annualMaximum: 500, lifetimeMaximum: null, copay: null, waitingPeriodDays: 0, preauthorizationRequired: false, notes: 'Naturopathic medicine. $500 annual maximum.' },
      ],
      exclusions: ['Cosmetic procedures', 'Experimental treatments'],
      claimsProcess: 'Submit claims online through mysunlife.ca or the Sun Life mobile app within 12 months of service.',
      renewalTerms: 'Automatically renews annually. Premiums may be adjusted at renewal.',
      sourceFile: 'Sunlife Healthcare Plan Documents/Enhanced Plan.md',
      extractionConfidence: 'high',
    },
    mlFeatures: {
      planId: 'sun-life-financial-sun-life-enhanced-plan',
      planName: 'Sun Life Enhanced Plan',
      planType: 'private_individual',
      carrier: 'Sun Life Financial',
      jurisdiction: 'Canada',
      monthlyPremiumEstimate: 195,
      deductible: 0,
      coinsuranceDefault: 90,
      maxOutOfPocket: 1500,
      totalBenefitCategories: 12,
      coveredBenefitCount: 12,
      preauthorizationRequiredCount: 0,
      coversPrescriptionDrugs: true,
      coversDental: true,
      coversVision: true,
      coversHospital: true,
      coversMentalHealth: true,
      coversEmergency: true,
      coversTravelMedical: true,
      coversSpecialist: true,
      coversPhysiotherapy: true,
      coversChiropractic: true,
      avgReimbursementPct: 92,
      minReimbursementPct: 80,
      maxReimbursementPct: 100,
      isPublic: false,
      hasIncomeRequirement: false,
      hasResidencyRequirement: true,
      hasWaitingPeriod: false,
      exclusionCount: 2,
      hasIncomeTieredCopay: false,
      overallGenerosity: 'premium',
      bestForProfile: 'Individuals and families with chronic conditions, high medication needs, or who want maximum coverage breadth including mental health and paramedical services.',
      featureVector: {
        plan_type: 'private_individual', jurisdiction: 'Canada', is_public: false,
        monthly_premium: 195, deductible: 0, coinsurance_default: 90, max_oop: 1500,
        covered_count: 12, total_categories: 12, coverage_ratio: 100, preauth_count: 0,
        covers_drugs: true, covers_dental: true, covers_vision: true, covers_hospital: true,
        covers_mental_health: true, covers_emergency: true, covers_travel: true,
        covers_specialist: true, covers_physio: true, covers_chiro: true,
        avg_reimbursement: 92, min_reimbursement: 80, max_reimbursement: 100,
        has_income_requirement: false, has_residency_requirement: true,
        has_waiting_period: false, exclusion_count: 2, has_income_tiered_copay: false,
        generosity: 'premium',
      },
    },
  },
  {
    sourceFile: 'What OHIP covers _ ontario.ca.md',
    planName: 'Ontario Health Insurance Plan (OHIP)',
    planType: 'provincial_public',
    carrier: 'Government of Ontario',
    jurisdiction: 'Ontario',
    extractionConfidence: 'high',
    extractedData: {
      planName: 'Ontario Health Insurance Plan (OHIP)',
      planType: 'provincial_public',
      carrier: 'Government of Ontario',
      jurisdiction: 'Ontario',
      effectiveDate: null,
      summary: 'Ontario\'s publicly funded health insurance program covering medically necessary hospital and physician services for eligible residents at no cost. The foundation of healthcare in Ontario, supplemented by private insurance for services not covered.',
      eligibility: {
        eligiblePopulations: ['Ontario residents', 'Canadian citizens', 'permanent residents', 'convention refugees', 'approved work permit holders'],
        ageRestrictions: null,
        residencyRequirements: 'Must be physically present in Ontario for 153 days in any 12-month period. New residents have a 3-month waiting period.',
        incomeRequirements: null,
        employmentRequirements: null,
        waitingPeriodDays: 90,
      },
      costStructure: {
        premiumType: 'free',
        monthlyPremiumEstimate: 0,
        deductible: 0,
        coinsuranceDefault: 100,
        maxOutOfPocket: 0,
        hasIncomeTieredCopay: false,
        incomeTiers: [],
      },
      benefits: [
        { category: 'hospital', covered: true, reimbursementPct: 100, annualMaximum: null, lifetimeMaximum: null, copay: null, waitingPeriodDays: 0, preauthorizationRequired: false, notes: 'All medically necessary inpatient and outpatient hospital services in standard ward.' },
        { category: 'emergency', covered: true, reimbursementPct: 100, annualMaximum: null, lifetimeMaximum: null, copay: null, waitingPeriodDays: 0, preauthorizationRequired: false, notes: 'All emergency department visits and ambulance services covered.' },
        { category: 'lab_diagnostic', covered: true, reimbursementPct: 100, annualMaximum: null, lifetimeMaximum: null, copay: null, waitingPeriodDays: 0, preauthorizationRequired: false, notes: 'Medically necessary lab tests and diagnostic imaging when ordered by a physician.' },
        { category: 'specialist', covered: true, reimbursementPct: 100, annualMaximum: null, lifetimeMaximum: null, copay: null, waitingPeriodDays: 0, preauthorizationRequired: false, notes: 'Specialist physician visits covered with referral from family doctor.' },
        { category: 'prescription_drugs', covered: false, reimbursementPct: null, annualMaximum: null, lifetimeMaximum: null, copay: null, waitingPeriodDays: null, preauthorizationRequired: false, notes: 'Not covered except through Ontario Drug Benefit (ODB) for seniors 65+ and social assistance recipients.' },
        { category: 'dental', covered: false, reimbursementPct: null, annualMaximum: null, lifetimeMaximum: null, copay: null, waitingPeriodDays: null, preauthorizationRequired: false, notes: 'Not covered. Dental surgery in hospital may be covered if medically necessary.' },
        { category: 'vision', covered: false, reimbursementPct: null, annualMaximum: null, lifetimeMaximum: null, copay: null, waitingPeriodDays: null, preauthorizationRequired: false, notes: 'Eye exams covered for children under 20 and adults 65+. Not covered for ages 20-64.' },
        { category: 'mental_health', covered: true, reimbursementPct: 100, annualMaximum: null, lifetimeMaximum: null, copay: null, waitingPeriodDays: 0, preauthorizationRequired: false, notes: 'Psychiatrist visits covered. Psychologist visits NOT covered.' },
      ],
      exclusions: ['Prescription drugs (most ages)', 'Dental care', 'Vision care (ages 20-64)', 'Physiotherapy (most cases)', 'Cosmetic surgery', 'Private hospital rooms'],
      claimsProcess: 'Show your valid Ontario health card at the point of service. No claims submission needed for covered services.',
      renewalTerms: 'Coverage is continuous as long as residency requirements are met. Health card renewed every 5 years.',
      sourceFile: 'What OHIP covers _ ontario.ca.md',
      extractionConfidence: 'high',
    },
    mlFeatures: {
      planId: 'government-of-ontario-ohip',
      planName: 'Ontario Health Insurance Plan (OHIP)',
      planType: 'provincial_public',
      carrier: 'Government of Ontario',
      jurisdiction: 'Ontario',
      monthlyPremiumEstimate: 0,
      deductible: 0,
      coinsuranceDefault: 100,
      maxOutOfPocket: 0,
      totalBenefitCategories: 8,
      coveredBenefitCount: 5,
      preauthorizationRequiredCount: 0,
      coversPrescriptionDrugs: false,
      coversDental: false,
      coversVision: false,
      coversHospital: true,
      coversMentalHealth: true,
      coversEmergency: true,
      coversTravelMedical: false,
      coversSpecialist: true,
      coversPhysiotherapy: false,
      coversChiropractic: false,
      avgReimbursementPct: 100,
      minReimbursementPct: 100,
      maxReimbursementPct: 100,
      isPublic: true,
      hasIncomeRequirement: false,
      hasResidencyRequirement: true,
      hasWaitingPeriod: true,
      exclusionCount: 6,
      hasIncomeTieredCopay: false,
      overallGenerosity: 'moderate',
      bestForProfile: 'All Ontario residents — provides the foundation of healthcare coverage. Should be supplemented with private insurance for prescription drugs, dental, and vision.',
      featureVector: {
        plan_type: 'provincial_public', jurisdiction: 'Ontario', is_public: true,
        monthly_premium: 0, deductible: 0, coinsurance_default: 100, max_oop: 0,
        covered_count: 5, total_categories: 8, coverage_ratio: 63, preauth_count: 0,
        covers_drugs: false, covers_dental: false, covers_vision: false, covers_hospital: true,
        covers_mental_health: true, covers_emergency: true, covers_travel: false,
        covers_specialist: true, covers_physio: false, covers_chiro: false,
        avg_reimbursement: 100, min_reimbursement: 100, max_reimbursement: 100,
        has_income_requirement: false, has_residency_requirement: true,
        has_waiting_period: true, exclusion_count: 6, has_income_tiered_copay: false,
        generosity: 'moderate',
      },
    },
  },
  {
    sourceFile: 'Temporary health care coverage_ What is covered - Canada.ca.md',
    planName: 'Interim Federal Health Program (IFHP)',
    planType: 'temporary_coverage',
    carrier: 'Government of Canada',
    jurisdiction: 'Canada',
    extractionConfidence: 'high',
    extractedData: {
      planName: 'Interim Federal Health Program (IFHP)',
      planType: 'temporary_coverage',
      carrier: 'Government of Canada',
      jurisdiction: 'Canada',
      effectiveDate: null,
      summary: 'A federal program providing temporary health coverage to refugees, refugee claimants, and other protected persons who are not yet eligible for provincial health insurance. Covers essential and supplemental health services.',
      eligibility: {
        eligiblePopulations: ['Resettled refugees', 'Refugee claimants', 'Protected persons', 'Victims of human trafficking'],
        ageRestrictions: null,
        residencyRequirements: 'Must be in Canada and not yet eligible for provincial/territorial health insurance',
        incomeRequirements: null,
        employmentRequirements: null,
        waitingPeriodDays: 0,
      },
      costStructure: {
        premiumType: 'free',
        monthlyPremiumEstimate: 0,
        deductible: 0,
        coinsuranceDefault: 100,
        maxOutOfPocket: 0,
        hasIncomeTieredCopay: false,
        incomeTiers: [],
      },
      benefits: [
        { category: 'hospital', covered: true, reimbursementPct: 100, annualMaximum: null, lifetimeMaximum: null, copay: null, waitingPeriodDays: 0, preauthorizationRequired: false, notes: 'Hospital services and physician visits covered.' },
        { category: 'emergency', covered: true, reimbursementPct: 100, annualMaximum: null, lifetimeMaximum: null, copay: null, waitingPeriodDays: 0, preauthorizationRequired: false, notes: 'Emergency services fully covered.' },
        { category: 'prescription_drugs', covered: true, reimbursementPct: 100, annualMaximum: null, lifetimeMaximum: null, copay: null, waitingPeriodDays: 0, preauthorizationRequired: false, notes: 'Essential prescription medications covered.' },
        { category: 'dental', covered: true, reimbursementPct: 100, annualMaximum: null, lifetimeMaximum: null, copay: null, waitingPeriodDays: 0, preauthorizationRequired: false, notes: 'Emergency dental care and essential dental services.' },
        { category: 'vision', covered: true, reimbursementPct: 100, annualMaximum: null, lifetimeMaximum: null, copay: null, waitingPeriodDays: 0, preauthorizationRequired: false, notes: 'Essential vision care including eye exams and corrective lenses.' },
        { category: 'mental_health', covered: true, reimbursementPct: 100, annualMaximum: null, lifetimeMaximum: null, copay: null, waitingPeriodDays: 0, preauthorizationRequired: false, notes: 'Counselling and mental health services covered.' },
      ],
      exclusions: ['Elective procedures', 'Cosmetic treatments'],
      claimsProcess: 'Service providers bill IFHP directly. Patients show their IFHP certificate at the point of service.',
      renewalTerms: 'Coverage continues until the person becomes eligible for provincial/territorial health insurance.',
      sourceFile: 'Temporary health care coverage_ What is covered - Canada.ca.md',
      extractionConfidence: 'high',
    },
    mlFeatures: {
      planId: 'government-of-canada-ifhp',
      planName: 'Interim Federal Health Program (IFHP)',
      planType: 'temporary_coverage',
      carrier: 'Government of Canada',
      jurisdiction: 'Canada',
      monthlyPremiumEstimate: 0,
      deductible: 0,
      coinsuranceDefault: 100,
      maxOutOfPocket: 0,
      totalBenefitCategories: 6,
      coveredBenefitCount: 6,
      preauthorizationRequiredCount: 0,
      coversPrescriptionDrugs: true,
      coversDental: true,
      coversVision: true,
      coversHospital: true,
      coversMentalHealth: true,
      coversEmergency: true,
      coversTravelMedical: false,
      coversSpecialist: false,
      coversPhysiotherapy: false,
      coversChiropractic: false,
      avgReimbursementPct: 100,
      minReimbursementPct: 100,
      maxReimbursementPct: 100,
      isPublic: true,
      hasIncomeRequirement: false,
      hasResidencyRequirement: false,
      hasWaitingPeriod: false,
      exclusionCount: 2,
      hasIncomeTieredCopay: false,
      overallGenerosity: 'comprehensive',
      bestForProfile: 'Refugees, refugee claimants, and protected persons who are not yet eligible for provincial health insurance. Provides essential coverage at no cost during the transition period.',
      featureVector: {
        plan_type: 'temporary_coverage', jurisdiction: 'Canada', is_public: true,
        monthly_premium: 0, deductible: 0, coinsurance_default: 100, max_oop: 0,
        covered_count: 6, total_categories: 6, coverage_ratio: 100, preauth_count: 0,
        covers_drugs: true, covers_dental: true, covers_vision: true, covers_hospital: true,
        covers_mental_health: true, covers_emergency: true, covers_travel: false,
        covers_specialist: false, covers_physio: false, covers_chiro: false,
        avg_reimbursement: 100, min_reimbursement: 100, max_reimbursement: 100,
        has_income_requirement: false, has_residency_requirement: false,
        has_waiting_period: false, exclusion_count: 2, has_income_tiered_copay: false,
        generosity: 'comprehensive',
      },
    },
  },
]

async function main() {
  console.log('Seeding Canadian plans into ExtractedPlan table...')

  for (const plan of canadianPlans) {
    await prisma.extractedPlan.upsert({
      where: { sourceFile: plan.sourceFile },
      create: {
        sourceFile: plan.sourceFile,
        planName: plan.planName,
        planType: plan.planType,
        carrier: plan.carrier,
        jurisdiction: plan.jurisdiction,
        extractedData: plan.extractedData,
        mlFeatures: plan.mlFeatures,
        extractionConfidence: plan.extractionConfidence,
      },
      update: {
        planName: plan.planName,
        planType: plan.planType,
        carrier: plan.carrier,
        jurisdiction: plan.jurisdiction,
        extractedData: plan.extractedData,
        mlFeatures: plan.mlFeatures,
        extractionConfidence: plan.extractionConfidence,
      },
    })
    console.log(`  ✓ ${plan.planName} (${plan.carrier})`)
  }

  console.log(`\nSeeded ${canadianPlans.length} Canadian plans.`)
}

main()
  .catch((error) => {
    console.error('Failed to seed Canadian plans.', error)
    process.exitCode = 1
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
