import { notFound } from 'next/navigation'
import { prisma } from '@/lib/prisma'
import { PrintButton } from './print-button'

type MedicalItem = {
  name?: string
  rawText?: string
  condition?: string
  substance?: string
  factor?: string
  vaccine?: string
  dosage?: string
  frequency?: string
  reaction?: string
  severity?: string
  date?: string
  notes?: string
  relation?: string
  status?: string
  [key: string]: unknown
}

export default async function SharePage({
  params,
}: {
  params: Promise<{ token: string }>
}) {
  const { token } = await params

  // Look up the share link
  const shareLink = await prisma.medicalShareLink.findUnique({
    where: { token },
  })

  if (!shareLink || shareLink.expiresAt < new Date()) {
    notFound()
  }

  // Load the medical profile
  const profile = await prisma.medicalProfile.findUnique({
    where: { userId: shareLink.userId },
  })

  if (!profile) {
    notFound()
  }

  // Load user name
  const user = await prisma.user.findUnique({
    where: { id: shareLink.userId },
    select: { name: true },
  })

  const sections = [
    { title: 'Conditions', items: asArray(profile.conditions) },
    { title: 'Medications', items: asArray(profile.medications) },
    { title: 'Allergies', items: asArray(profile.allergies) },
    { title: 'Surgeries', items: asArray(profile.surgeries) },
    { title: 'Immunizations', items: asArray(profile.immunizations) },
    { title: 'Family History', items: asArray(profile.familyHistory) },
  ]

  return (
    <main className="min-h-screen bg-ivory px-4 py-8 print:bg-white print:px-0 print:py-4">
      <div className="mx-auto max-w-2xl">
        {/* Header */}
        <div className="mb-6 flex flex-col gap-1 border-b border-biscuit pb-4 print:border-black/20">
          <p className="font-cormorant text-[16px] italic tracking-[0.15em] text-driftwood">
            CareBridge AI
          </p>
          <h1 className="font-cormorant text-[28px] italic leading-tight text-espresso">
            Medical Summary
          </h1>
          {user?.name && (
            <p className="font-serif text-[15px] text-driftwood">
              Patient: <span className="font-medium text-espresso">{user.name}</span>
            </p>
          )}
          <p className="font-serif text-[12px] text-sandstone">
            Generated {new Date().toLocaleDateString()} &middot; Expires{' '}
            {shareLink.expiresAt.toLocaleDateString()} at{' '}
            {shareLink.expiresAt.toLocaleTimeString()}
          </p>
        </div>

        {/* Sections */}
        <div className="flex flex-col gap-5">
          {sections.map((section) => (
            <div key={section.title}>
              <h2 className="mb-2 font-serif text-[13px] font-medium uppercase tracking-[0.18em] text-driftwood print:text-black/60">
                {section.title}
              </h2>
              {section.items.length > 0 ? (
                <div className="flex flex-col gap-1.5">
                  {section.items.map((item, i) => (
                    <div
                      key={i}
                      className="rounded-button border border-biscuit bg-parchment px-3 py-2 print:rounded-none print:border-black/10 print:bg-transparent"
                    >
                      <p className="font-serif text-[14px] text-espresso">
                        {itemName(item)}
                      </p>
                      {itemDetail(item) && (
                        <p className="font-serif text-[12px] text-driftwood">
                          {itemDetail(item)}
                        </p>
                      )}
                    </div>
                  ))}
                </div>
              ) : (
                <p className="font-serif text-[13px] italic text-sandstone">
                  None recorded
                </p>
              )}
            </div>
          ))}
        </div>

        {/* Footer */}
        <div className="mt-8 border-t border-biscuit pt-3 print:border-black/20">
          <p className="font-serif text-[11px] leading-[1.5] text-sandstone print:text-black/40">
            This document was generated by CareBridge AI from patient-reported
            data. It is not a substitute for professional medical records.
            Verify all information with the patient.
          </p>
        </div>

        {/* Print button (hidden in print) */}
        <PrintButton />
      </div>
    </main>
  )
}

function asArray(value: unknown): MedicalItem[] {
  return Array.isArray(value) ? value : []
}

function itemName(item: MedicalItem): string {
  return String(
    item.name ??
    item.rawText ??
    item.condition ??
    item.substance ??
    item.factor ??
    item.vaccine ??
    'Unknown',
  )
}

function itemDetail(item: MedicalItem): string | null {
  const parts: string[] = []
  if (item.dosage) parts.push(item.dosage)
  if (item.frequency) parts.push(item.frequency)
  if (item.reaction) parts.push(`Reaction: ${item.reaction}`)
  if (item.severity) parts.push(`Severity: ${item.severity}`)
  if (item.status) parts.push(item.status)
  if (item.date) parts.push(item.date)
  if (item.relation) parts.push(item.relation)
  if (item.notes) parts.push(item.notes)
  return parts.length > 0 ? parts.join(' · ') : null
}
